### ISSUE TITLE
Is it possible to be compatible with servlet 2.5

### ISSUE THREAD

**Issue by matrixcloud** [socketio/engine.io-server-java#15]
Hi,

Is it possible to be compatible with servlet 2.5?

Thanks,
Atom

**Comment by trinopoty** [comment]
The servlet 2.5 spec does not provide a lot of core functionality required by engine.io.
For instance, Async support was not available in servet 2.5 spec along with websocket support.
Although you can live without both of those, the async is considered a required feature because without it, the client library sends lots of requests to the server (#11) causing a DoS.

In conclusion, it would be rather cumbersome to support servlet 2.5 spec. If you must use the servlet 2.5 spec, you can try using a node.js bridge for your socket.io connections.

**Comment by matrixcloud** [comment]
@trinopoty  i see, thanks.
