### ISSUE TITLE
getInitialHeaders and getInitialQuery returns null

### ISSUE THREAD

**Issue by tuzzmaniandevil** [socketio/engine.io-server-java#29]
When an `EngineIoSocket` gets created from a web request, The socket gets initialize before the transport runs `onRequest`. Which means the `mInitialQuery` and `mInitialHeaders` are null are they get pulled from the transport which doesn't have those values yet

```java
final EngineIoSocket socket = new EngineIoSocket(lockObject, sid, this, mScheduledExecutor);
final Transport transport = new Polling(lockObject);
socket.init(transport, request);
transport.onRequest(request, response);
```

**Comment by trinopoty** [comment]
This issue has been noted. I'll notify here when I release a version with the fix.

**Comment by rabihbeyrouty** [comment]
@trinopoty would you please tell us when this fix will be available .

**Comment by trinopoty** [comment]
I had a look at it and this issue doesn't seem to effect any public facing api. Since the socket is already fully initialized when it's reported via the `connection` event, this issue should be invisible to any code that uses the socket.
Can you provide a minimal example where a code using the socket will receive null values for the query and headers?

**Comment by trinopoty** [comment]
Ok. I figured out the issue. Expect to see a new version on maven in a few hours.

**Comment by rabihbeyrouty** [comment]
@trinopoty many thanks
