### ISSUE TITLE
Version compatibilities

### ISSUE THREAD

**Issue by manikmagar** [socketio/engine.io-server-java#41]
I couldn't find a confirmed version compatibility table but is 5.x version compatible with 1.x server and client libraries for Socket io v2.x? Or, its better to stay with 1.x of engine.io? Basically following configuration -
```
        <socket.io-client.version>1.0.1</socket.io-client.version>
        <socket.io-server.version>1.0.3</socket.io-server.version>
        <engine.io-server.version>5.0.0</engine.io-server.version>
        <jetty-server.version>9.4.19.v20190610</jetty-server.version>
```

I am looking for two features from latest - adding handshake interceptor and setting executor service for server.
TIA!

**Comment by trinopoty** [comment]
The java server libraries maintain compatibility with major versions of the js library. For instance, v5 of the engine.io server library is compatible with v5 of the engine.io js library. v4 java library is compatible with v4 js library. Same applies for the socket.io library.

I'm not aware of the compatibility between versions of the java client library since that follows different versioning conventions.

**Comment by manikmagar** [comment]
Sorry for the delayed response but your comment is helpful, Thanks!
